### ISSUE TITLE
Why video dataset is different to image dataset in the fixed layer？

### ISSUE THREAD

**Issue by Freedomxt** [Yu-Wu/One-Example-Person-ReID#2]
for example：
dataset market1501：the fixed_layer = False
dataset MARS: the fixed_layer = True

**Comment by Yu-Wu** [comment]
@Freedomxt 
Thanks for your interest.
It is due to the GPU memory limit. For video dataset, each data input is a 16-frame video, which requires much more GPU memory than the image one.
If you have a large GPU memory (such as 32G), you could set all the fixed_layer to be False. It will produce better performance.

**Comment by Freedomxt** [comment]
> @Freedomxt
> Thanks for your interest.
> It is due to the GPU memory limit. For video dataset, each data input is a 16-frame video, which requires much more GPU memory than the image one.
> If you have a large GPU memory (such as 32G), you could set all the fixed_layer to be False. It will produce better performance.

Thanks for you reply!
