### ISSUE TITLE
How to reproduce?

### ISSUE THREAD

**Issue by Ensoleille** [Yu-Wu/One-Example-Person-ReID#4]
Hello, thank you for sharing, but I run the error after following the readme file.
NotADirectoryError: [Errno 20] Not a directory: '/home/Ensoleille/One-Example-Person-ReID-master/data/market1501/train/0002_c1s1_000451_03.jpg'.I hope you can tell me how to reproduce smoothly.

**Comment by Yu-Wu** [comment]
@Ensoleille 

Hi, it is due to the data issue.

Please download the data for Market-1501: http://45.32.69.75/share/market1501.tar
And then move the tar to "/home/Ensoleille/One-Example-Person-ReID-master/data/" and unzip here.

We re-generate the Market-1501 dataset to a video-like style for a better usage in our code.

**Comment by Ensoleille** [comment]
Hello,thanks for answering, the above problem has been solved
@Yu-Wu
